name: DRAGui
main: io.github.invigoratedcat.dragui.DRAGui
version: 1.0.1
commands:
 drag: 
    description: This is a command my dude
    usage: /drag <args>
    permission: DRAGui.drag
    permission-message: You can't use my commands you cunt.
    
permissions:
  DRAGui.drag:
    description: yes
    default: true